"""Regenerate the Rust wire-format conformance test from generated sources.

Emits schema/generated/phds-rust/tests/wire_format.rs with one round-trip
assertion per permissible value of every vocabulary enum. Variant names are
parsed out of the generated lib.rs (each variant's serde(rename) attribute
pairs the wire value with the exact Rust identifier gen-rust chose), not
re-derived here — so Rust keyword escaping, casing, and any future naming
rules can never diverge from the generator's. phds.schema.json provides the
authoritative enum/value census; a mismatch in either direction is an error.

Runs as part of `just gen` (after gen-rust);
tests/test_generated_contract.py census-checks the result.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "schema" / "generated"

ENUM_RE = re.compile(r"pub enum (\w+) \{(.*?)\n\}", re.DOTALL)
VARIANT_RE = re.compile(
    r'serde\(rename = "((?:[^"\\]|\\.)*)"\)\)\]\s*\n\s*(r#)?(\w+),'
)

HEADER = """\
// Canonical wire-format conformance for generated enums. Generated by
// tools/gen_wire_format_test.py from phds.schema.json + lib.rs — edit
// there, not here. Lives outside src/ so `gen-rust --force` (which
// rewrites src/, Cargo.toml, pyproject.toml) never touches it.
//
// The exhaustive test below enumerates every permissible value of every
// vocabulary enum in phds.schema.json ({n_variants} variants across {n_enums} enums);
// tests/test_generated_contract.py census-checks that this stays in sync
// with the schema.
#![cfg(feature = "serde")]

use phds::*;

fn assert_round_trip<T>(value: T, wire: &str)
where
    T: serde::Serialize + serde::de::DeserializeOwned + PartialEq + core::fmt::Debug,
{
    let encoded = serde_yml::to_string(&value).expect("serialize");
    assert_eq!(encoded.trim(), wire, "serialize {value:?}");
    let decoded: T = serde_yml::from_str(wire).expect("deserialize");
    assert_eq!(decoded, value, "deserialize {wire:?}");
}

#[test]
fn all_enum_variants_round_trip_canonical_wire_values() {
"""


def rust_enum_variants(lib_rs: str) -> dict[str, dict[str, str]]:
    """enum name -> {wire value -> Rust variant path segment}."""
    enums: dict[str, dict[str, str]] = {}
    for enum_match in ENUM_RE.finditer(lib_rs):
        name, body = enum_match.group(1), enum_match.group(2)
        variants = {
            wire: (raw or "") + ident
            for wire, raw, ident in VARIANT_RE.findall(body)
        }
        if variants:
            enums[name] = variants
    return enums


def main() -> None:
    schema = json.loads((GENERATED / "phds.schema.json").read_text(encoding="utf-8"))
    schema_enums = {
        name: d["enum"]
        for name, d in sorted(schema["$defs"].items())
        if d.get("type") == "string" and "enum" in d
    }
    lib_rs = (GENERATED / "phds-rust" / "src" / "lib.rs").read_text(encoding="utf-8")
    rust_enums = rust_enum_variants(lib_rs)

    lines = []
    for name, values in schema_enums.items():
        if name not in rust_enums:
            raise SystemExit(f"enum {name} in phds.schema.json has no serde renames in lib.rs")
        rust = rust_enums[name]
        missing = [v for v in values if v not in rust]
        if missing:
            raise SystemExit(f"enum {name}: values {missing} have no serde rename in lib.rs")
        extra = sorted(set(rust) - set(values))
        if extra:
            raise SystemExit(f"enum {name}: lib.rs renames {extra} not in phds.schema.json")
        for wire in values:
            escaped = wire.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    assert_round_trip({name}::{rust[wire]}, "{escaped}");')

    body = HEADER.replace("{n_variants}", str(len(lines))).replace(
        "{n_enums}", str(len(schema_enums))
    )
    out = GENERATED / "phds-rust" / "tests" / "wire_format.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body + "\n".join(lines) + "\n}\n", encoding="utf-8")
    print(f"wire_format.rs: {len(lines)} variants across {len(schema_enums)} enums")


if __name__ == "__main__":
    main()
